nome = input('\033[32mDigite o seu nome completo: \033[34m').strip().title()
print(f'\033[mAnalisando seu nome...')
print(f'\033[35mseu nome em maiúsculas é {nome.upper()}.')
print(f'Seu nome em minúsculas é {nome.lower()}.')
print(f'Seu nome tem ao todo {len(nome) - nome.count(" ")} letras.')
separa = nome.split()
print(f'Seu primeiro nome é {separa[0]} e ele tem {len(separa[0])} letras\033[m.')
