a = input('\033[47;32;1mDigite algo:\033[m\033[33m ')
print('\033[31m\nO tipo primitivo desse valor é: ', type(a))
print('Só existem espaços? ', a.isspace())
print('é um número? ', a.isnumeric())
print('É alfabetico', a.isalpha())
print('É alfanúmerico? ', a.isalnum())
print('Está em maiúsculas? ', a.isupper())
print('Está em minúsculas? ', a.islower())
print('Está capitalizada? ', a.istitle())
print('\033[m')
